# This YAML file contains configmap objects,
# which are necessary to run csi opensds plugin.

kind: ConfigMap
apiVersion: v1
metadata:
  name: csi-configmap-opensdsplugin
data:
  opensdsendpoint: http://207.148.122.215:50040
  opensdsauthstrategy: keystone
  osauthurl: http://207.148.122.215/identity
  osusername: admin
  ospassword: opensds@123
  ostenantname: admin
  osprojectname: admin
  osuserdomainid: default
  
